### ISSUE TITLE
Update logo repo with accurate logos

### ISSUE THREAD

**Issue by nadonomy** [vector-im/design#1]
- Our [public logos repo](https://github.com/vector-im/logos/tree/master/element) has old Element logo assets. While developing the brand we originally didn't have the mark encapsulated in a circle, and never got round to updating the assets everywhere. We need to:
    - Export logos from 'Brand guidelines' following the existing [styles and naming conventions, and broadly the same useful dimensions](https://github.com/vector-im/logos/tree/master/element)
    - Update the repo

**Comment by nadonomy** [comment]
@JordanConnor for this, best to create a PR with the updated logo assets and shoot me a DM with a link to review/merge in.

If you're not 100% sure on how to do this let me know and you could always throw me a zip with the assets and I can commit from there1

**Comment by JordanConnor** [comment]
https://github.com/vector-im/logos/pull/9
