### ISSUE TITLE
MsgBubbles: Dark mode

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/design#10]
In dark mode, what colours should the message bubbles be?

**Comment by ganfra** [comment]
I guess for incoming messages we can take the background of reactions?

**Comment by amshakal** [comment]
Link to figma: https://www.figma.com/file/zVtAKK0hzKu5JkpbzlE1pG/Message-Bubbles?node-id=1937%3A43684

The green colour is subject to change shortly. The rest will remain the same. Reactions take the same colour as the bubble depending on what side it is. The pressed state is the same as it is currently on timeline without bubbles

**Comment by daniellekirkwood** [comment]
Closing as action completed
