### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by spacefleet-TSGT-HE** [vector-im/design#12]
I'm interested to element, I want to use it,
For our purpose we need custom some ui-ux 
so I need to access into ui-ux assets to prototype (sketch or figma or others...) 
it's save our time to design from scratch,
please invite me with this email hasanebrahimi036@gmail.com
Thanks a lot

**Comment by janogarcia** [comment]
Hi Hasan, we can't give general access to all the design files on Figma.

We may be able to do this in the future once we have cleaned up the files, added all the missing stuff, and have a more precise separation between private and public files. But we, unfortunately, aren't at that point yet.

We'd love to share such a helpful resource and make it available for the community of users, but it simply doesn't exist yet.

/cc @nadonomy

**Comment by janogarcia** [comment]
In the meantime, as a workaround, if you are only looking into doing light design/theming changes (colors, typography, logos... but you could also style basically any component with CSS) to the Web client I'd suggest creating a custom theme with CSS:

https://github.com/matrix-org/matrix-react-sdk#developer-guide

If you have further questions on how to do that I'd suggest asking in the `#element-web:matrix.org` room.

**Comment by nadonomy** [comment]
> We may be able to do this in the future once we have cleaned up the files, added all the missing stuff, and have a more precise separation between private and public files. But we, unfortunately, aren't at that point yet.
> 
> We'd love to share such a helpful resource and make it available for the community of users, but it simply doesn't exist yet.

+1.

I'd love to open up access to the designs but unfortunately Figma's permissions are too leaky— it's possible to gain access to browse confidential data.

In future, we'll have a clearer separation of concerns and will be able to share files using [Figma community](https://www.figma.com/community). However, the effort to do so is non trivial so we can't commit to any timeline.
