### ISSUE TITLE
App Layout: Empty States

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/design#24]
As part of the new app layout rollout we'll need updated Empty States.
This is a part of: https://github.com/vector-im/element-meta/issues/218

This issue will become the requirements for the empty states but @daniellekirkwood is still working on them

We need an empty state for when:
* the user is on home: all chats
* the user is in a space
* the user has selected the unreads filter, but there are no unreads

(All other empty states, such as a filter, room list etc. will remain the same)

[New]
* We may need an empty state for Rooms and People tab (or we may reuse what we have) 
* We also need an empty state for when a user has no spaces

**Comment by daniellekirkwood** [comment]
Suggestions for copy: 

**A generic empty state where either Filters are off, or "All" is selected:**
_In All Chats (Home)_
>Welcome < displayname >.
>Create a chat, or join an existing room, to get started.

_In a Space: 3 options_
>Something's missing... 
>Add an existing room, or create a new one, to get started.

>It's looking a little empty. 
>Add an existing room, or create a new one, to get started.

>It's quiet... Too quiet
>Add an existing room, or create a new one, to get started.

**A message for when Unreads is empty: 4 options**
> All caught up!
> If you send a message, you might get one back.

> Nothing to see here
> Move along

> Nothing to report
> This is where you're unread messages will show up, when you have some

> Woohoo!
> You're all caught up

**Comment by amshakal** [comment]
There are four empty states that were discussed. I have two of them ready and two if them are pending final illustrations. If we can add a placeholder image that can be replaced later, we can work on all of them now.

1. All chats screen with no rooms yet - Content is finalised, Pending illustration
2. Space screen with no rooms added to the space - Content is finalised, Pending illustration
3. When there are no unreads in the tab - Ready
4. When there are no spaces (emoty space switcher bottom sheet) - Ready

[Link to iOS empty states](https://www.figma.com/file/Hw4gjP3pknMZUir8jQqmWH/%5BMobile%5D-IA-early-proposals?node-id=3608%3A168944)
[Link to Android empty states](https://www.figma.com/file/Hw4gjP3pknMZUir8jQqmWH/%5BMobile%5D-IA-early-proposals?node-id=3609%3A169367)
