### ISSUE TITLE
App Layout Release Experience

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/design#25]
We need to manage the release experience of the new app layout to existing users. 

This issue will discuss how we might do that. 

https://github.com/vector-im/element-meta/issues/218

What are the other things we can do? 
We **need** to ensure that we give people warning and handholding that the app is changing/changed so that we minimise the impact to retention.

<hr />

Danielle's idea: When the user opens the app for the first time after updating to the new version, they're shown a full screen takeover with content that explains whats happened - could also link to a blog post?

**Designs**
- [Android](https://www.figma.com/file/DQq9Qi8rRJ7cBPFt98uDAM/App-layout-release-xp?node-id=57%3A5809)
- [iOS](https://www.figma.com/file/DQq9Qi8rRJ7cBPFt98uDAM/App-layout-release-xp?node-id=57%3A6871)

No animations involved, just still images.

Thanks to @fedrunov [suggestion](https://github.com/vector-im/design/issues/25#issuecomment-1218220371) - the images in the screens are transparent so should work ok for all themes.

Other options - an in-app notifications (unsure technical feasibility)

**Comment by daniellekirkwood** [comment]
Here are some examples I've experienced in the last few weeks:

![IMG_2896](https://user-images.githubusercontent.com/89144281/183424796-329bc7b5-6fd5-4576-a7fa-9541255089e7.PNG)


![IMG_2842](https://user-images.githubusercontent.com/89144281/183424866-b13568be-55e3-4a6d-a136-7151c83affe3.PNG)


![IMG_2841](https://user-images.githubusercontent.com/89144281/183424910-3da0cb0c-835e-4d6c-b808-e3e41674cd51.PNG)

**Comment by daniellekirkwood** [comment]
@niquewoodhouse please coordinate with devs on the feasibility of the options ahead of launch - nothing is too much from a product perspective but I'm unsure of our app's capabilities. 

Let me know when/if you need support.

**Comment by niquewoodhouse** [comment]
**Few first ideas:**

> please coordinate with devs on the feasibility of the options ahead of launch - nothing is too much from a product perspective but I'm unsure of our app's capabilities.

@gileluard would you mind commenting on these ideas - in terms of feasibility please?  @fedrunov I'm happy to do android versions, unless you're able to guestimate feasibility from these.

Dialog 01
<img width="375" alt="dialog-01@2x" src="https://user-images.githubusercontent.com/1587166/184360031-3e3ae89b-fda1-4559-b12e-4935bdbb9a18.png">

Anchored sheet 01
<img width="375" alt="anchor-sheet-02 1@2x" src="https://user-images.githubusercontent.com/1587166/184360122-2a0d514e-3eea-401a-972e-c9453a7dfcc5.png">

<img width="375" alt="anchor-sheet-02 2@2x" src="https://user-images.githubusercontent.com/1587166/184360980-8088f671-706a-46a9-ba15-0a0053621be9.png">

Anchored sheet 02

<img width="375" alt="anchor-sheet-03@2x" src="https://user-images.githubusercontent.com/1587166/184361018-1da7713a-e2fe-49db-ad40-c12ce13cda67.png">


Anchored sheet 03

https://user-images.githubusercontent.com/1587166/184361067-2f74b351-4a2c-4895-930b-f36cadff8210.mov

**Comment by daniellekirkwood** [comment]
Thanks Nique! 

A couple of thoughts: 
- In the GIF there we have English words, these would need to be translated and that's probably out of scope for this experience. 
- The bottom sheet feels great - it gives us the ability to do the swipe you've suggested which feels like a great way to introduce several changes without being overwhelming. It's also cleaner and less distracting.
- Ideally the Read More would link to the blog but I'm unsure we'd be able to handle this timing wise :)

**Comment by daniellekirkwood** [comment]
Also, the content of the carousel shouldn't jump straight into the changes. It should start with an intro: "Hey! Somethings will look new around here, swipe to learn more" followed by the big changes, for example :)

**Comment by niquewoodhouse** [comment]
Thanks @daniellekirkwood based on your feedback here are new designs.  

- [iOS](https://www.figma.com/file/DQq9Qi8rRJ7cBPFt98uDAM/App-layout-release-xp?node-id=41%3A3060)
- [Android](https://www.figma.com/file/DQq9Qi8rRJ7cBPFt98uDAM/App-layout-release-xp?node-id=42%3A4929)

I'm not sure of what features we should be introducing but I gave it a go.  Please feel free to comment/edit to change copy/suggest anything.

@amshakal would you like any amends? @fedrunov @gileluard can you comment on feasibility of these ideas please, thanks

**Comment by gileluard** [comment]
@niquewoodhouse 

The design looks great! What does the button `show me`?
About the animations, they are complex and I believe we'll need to use animated GIF even if the format is not natively supported by iOS (format TBD)

**Comment by amshakal** [comment]
@niquewoodhouse  Love where you have landed. I added a small comment about where feedback button on Android would be, else it all looks good to me.

We could add a secondary CTA for 'Read More' that can link to the blog post about the new layout. 

And if animations would take time, we can stick to static images.

**Comment by ericdecanini** [comment]
@niquewoodhouse love the designs (looking at Android specifically)! It's very Android-standard and feels intuitive as to what a "hey look at this new feature" should be.

Animations would definitely take a bit more time than static images. If we did want to do them:
1) We definitely shouldn't do text in the animation for the language reasons already mentioned
2) They should be subtle as not to be overwhelming with all the other new elements displayed on screen

That being said I see no problem with it being static

**Comment by fedrunov** [comment]
@niquewoodhouse Looks great! Clean and smooth, I really like it, and it's also in touch with our onboarding on welcome screen. 

Couple notes:

- We need to be sure images looks good in every theme, so, either different set of images or maybe transparent background? 🤔 
- Animations are good, but could bring some problems on specific devices (especially in case of transparent background), so I'd not take risk including them just before release 
- Do we think this will be only for this feature or we plan to reuse it later? It looks like good pattern for announcing significant updates for users, so we could make it easier to replace images and copies + provide different amount of slides. Will take slightly more time, but i think it's worth it

**Comment by daniellekirkwood** [comment]
Great conversation! 

Let's:
* Stick to static images
* Make sure that one set of images works for both dark and light mode

@fedrunov I think it would be cool to have this pattern again, how much longer would it take to build to be reusable? Hours more or days more?

I'll take a crack at suggesting some copy changes now

**Comment by gsouquet** [comment]
Closing as the design side of things has been resolved
