### ISSUE TITLE
Threads: Can't decrypt messages

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/design#8]
When the user hasn't shared tokens across platforms, there may be some messages that cannot be decrypted. 
This was raised by Aris in standup but the same applies to Web.

- [ ] We need to confirm that this message is fine to show in timeline and in thread timeline
- [ ] We need to know how to display the Root message event in the Thread list if it can't be viewed or decrypted

| Web screenshot | Android screenshot | 
|------|------|
| <img width="347" alt="webundecrypted" src="https://user-images.githubusercontent.com/89144281/146032127-0ce939b2-e988-40ae-be58-cdcfb62e7cbb.png"> | insert screenshot |

**Comment by janogarcia** [comment]
@daniellekirkwood I think we should reuse the same error messages we use for decryption errors in the main timeline. While those are far from perfect, redesigning how we handle those across the app would be a major undertaking, out of the scope for Threads P0. I'll try to add a mockup for that at some point for completeness, but let's settle for that for P0, even if not ideal.

That said, that screenshot for Web is missing the thread icons in the summary, which seems to be an unrelated issue. Probably something that only affected a previous iteration.

**Comment by daniellekirkwood** [comment]
"Fallback for incomplete threads".

https://github.com/vector-im/element-web/issues/19762

iOS
https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=3267%3A338027

Android
https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=3267%3A335887

**Comment by daniellekirkwood** [comment]
@janogarcia I updated this issue with the information you sent to me, thanks!

**Comment by janogarcia** [comment]
@daniellekirkwood The "incomplete threads" issue has actually no relation with this one, though. On the first one, you can't fetch the content (you can't event check if it really exists), on the second one you can fetch the message (the message exists, and you are allowed to retrieve it) but you can decrypt it.
